### PR TITLE
Octolapse hooks v2

### PR DESCRIPTION
**Pull request by FormerLurker**
Adds two custom hooks for Octolapse, and the ability to add new hooks on demand via the Dropbox Timelapse settings page.  Resolves issue #7.

Also adds popup toasts which resolve issue #1.

### CODE REVIEW

**Review by jslay88 — APPROVED** [review]
Thanks for all the hard work. Feel free to merge and release before I get to it.

**Comment by FormerLurker** [comment]
I was more than happy to do so, and will merge as soon as I am off mobile!

**Comment by FormerLurker** [comment]
@SamKemp, thank you for your contribution as well!  I found them more than useful enough to include your commits.

**Comment by FormerLurker** [comment]
@jslay88, we missed something in the review.  I forgot to bump the version to 0.1.3, and can't delete the release or the tag.  Perhaps you can do this and recreate the release?  Also, you can delete the branches you no longer need.

**Comment by jslay88** [comment]
Will do when I get the chance. If we have to rerelease under .4 so be it.

**Comment by FormerLurker** [comment]
Shouldn't have to..  just delete the release first (save the markdown), then the tag, then recreate after bumping the version.  The only issue now is that until the version is updated, octoprint will keep saying a new version is available.  Sorry for the hassle!

**Pull request merged**
